spring:
  profiles:
    group:
      "local": "localdb, common"

---

spring:
  profiles:
    group:
      "dev": "devdb, common"

---

spring:
  profiles:
    group:
      "prod": "proddb, common"

---

spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---

spring:
  config:
    activate:
      on-profile: "localdb"
  datasource:
    url: jdbc:h2:~/imgo
    username: imgo
    password:
    driver-class-name: org.h2.Driver
