spring:
  profiles:
    group:
      "local": "localdb,common"

---

spring:
  profiles:
    group:
      "dev": "devdb,common"
    include: "oauth"

---

spring:
  profiles:
    group:
      "prod": "proddb,common"
    include: "oauth"

---

spring:
  profiles:
    group:
      "test": "testdb,common"

---

spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
  # session 을 db에 저장
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---

spring:
  config:
    activate:
      on-profile: "localdb"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: "devdb"
  datasource:
    url: ENC(65ZFRXaMWykX9ii4MmNFKQTSbGVs5O3mehkJgJZMTHG1i64dLEn5OeaXBzufTrfD)
    username: ENC(R59JJdfpkFxYEUeZfhcJbg==)
    password: ENC(mRrCFDTbYd0zO3NrtDx7MVKlt3lnY5gEgCCCicM+j0M=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false


---

spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    url:
    username: imgo
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: "testdb"
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password:
    driver-class-name: org.h2.Driver