# application-oauth.yml 을 만들면, 스프링부트에서 key-value 형태로
# profile: oauth 를 저장하여 관리함
# application.yml 에 profile=oauth 로 불러올 수 있음
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            # Encryption 필요
            client-id: ENC(acrzec47moEOeZ1hyRLQltT7s4qQz4xsvuIcsOP47TAx5Qd6R2UMFqFdWlDriyFqqt/gOR2Z2NGN0NUdyc/L3RpQ4BR4oHcvPvHGDo3MSTbALlC1bksHyA==)
            client-secret: ENC(q2LsBAvyUk/C03rK7Mdf4+JBnx7mXo6hXrcRO/QQMd3Hk+pDovVxBQ==)
            scope: profile, email
